#!/bin/bash

# Search the site 1337x.to for magnet links
# If search string is multiple worded, put it into parentheses "example search string"
# Outputs magnet link to be used with any torrent client
# Usage: <script> <search_string>

exit_err() {
		echo "$1"
		exit 1
}

[ -z "$1" ] && exit_err "Usage: <script> <search_string>"

IFS=$'\n'
SEARCH_STRING="$(echo "https://1337x.to/search/"$@"/1/" | sed 's/\ /+/g')"
RESULT="$(curl -s "$SEARCH_STRING" | grep -P -o '/torrent/[^"]*')"

[ -z "$RESULT" ] && exit_err "No torrent found."

# Select a torrent from a list of torrents found
####################################################################
# By default the select statement's output is printed to stderr (2)#
####################################################################
select torrent in $RESULT; do
	TORRENT_LINK="https://1337x.to$torrent"
	curl -s "$TORRENT_LINK" | grep -m 1 -P -o 'magnet[^"]*'
	break
done
